//
// V3BulkDeparturesRouteDirectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3BulkDeparturesRouteDirectionResponse: Codable {

    /** Route identifier */
    public var routeId: String?
    /** Direction of travel identifier */
    public var directionId: Int?
    /** Name of direction of travel */
    public var directionName: String?

    public init(routeId: String?, directionId: Int?, directionName: String?) {
        self.routeId = routeId
        self.directionId = directionId
        self.directionName = directionName
    }

    public enum CodingKeys: String, CodingKey { 
        case routeId = "route_id"
        case directionId = "direction_id"
        case directionName = "direction_name"
    }


}

