//
// V3BulkDeparturesStopResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3BulkDeparturesStopResponse: Codable {

    /** Name of stop */
    public var stopName: String?
    /** Stop identifier */
    public var stopId: Int?
    /** Geographic coordinate of latitude at stop */
    public var stopLatitude: Float?
    /** Geographic coordinate of longitude at stop */
    public var stopLongitude: Float?
    /** suburb of stop */
    public var stopSuburb: String?

    public init(stopName: String?, stopId: Int?, stopLatitude: Float?, stopLongitude: Float?, stopSuburb: String?) {
        self.stopName = stopName
        self.stopId = stopId
        self.stopLatitude = stopLatitude
        self.stopLongitude = stopLongitude
        self.stopSuburb = stopSuburb
    }

    public enum CodingKeys: String, CodingKey { 
        case stopName = "stop_name"
        case stopId = "stop_id"
        case stopLatitude = "stop_latitude"
        case stopLongitude = "stop_longitude"
        case stopSuburb = "stop_suburb"
    }


}

