//
// V3BulkDeparturesUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3BulkDeparturesUpdateResponse: Codable {

    public enum RouteDirectionStatus: Int, Codable {
        case _0 = 0
        case _1 = 1
    }
    /** Timetabled and real-time service departures */
    public var departures: [V3Departure]?
    /** Transport mode identifier */
    public var routeType: Int?
    /** Stop identifier */
    public var stopId: Int?
    public var requestedRouteDirection: V3BulkDeparturesRouteDirectionResponse?
    /** The status of the route direction (changed | unchanged).              If changed, requests should change the requested_route_direction for the route_direction supplied. */
    public var routeDirectionStatus: RouteDirectionStatus?
    public var routeDirection: V3BulkDeparturesRouteDirectionResponse?

    public init(departures: [V3Departure]?, routeType: Int?, stopId: Int?, requestedRouteDirection: V3BulkDeparturesRouteDirectionResponse?, routeDirectionStatus: RouteDirectionStatus?, routeDirection: V3BulkDeparturesRouteDirectionResponse?) {
        self.departures = departures
        self.routeType = routeType
        self.stopId = stopId
        self.requestedRouteDirection = requestedRouteDirection
        self.routeDirectionStatus = routeDirectionStatus
        self.routeDirection = routeDirection
    }

    public enum CodingKeys: String, CodingKey { 
        case departures
        case routeType = "route_type"
        case stopId = "stop_id"
        case requestedRouteDirection = "requested_route_direction"
        case routeDirectionStatus = "route_direction_status"
        case routeDirection = "route_direction"
    }


}

