//
// V3BulkDeparturesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3BulkDeparturesRequest: Codable {

    public enum Expand: String, Codable {
        case all = "All"
        case stop = "Stop"
        case route = "Route"
        case run = "Run"
        case direction = "Direction"
        case disruption = "Disruption"
    }
    /** Collection of departure requests */
    public var requests: [V3StopDepartureRequest]
    /** Filter by the date and time of the request (ISO 8601 UTC format) (default &#x3D; current date and time) */
    public var dateUtc: Date?
    /** Indicates if filtering runs (and their departures) to those that arrive at destination before date_utc (default &#x3D; false). Requires max_results &amp;gt; 0. */
    public var lookBackwards: Bool?
    /** Indicates if cancelled services (if they exist) are returned (default &#x3D; false) - metropolitan train only */
    public var includeCancelled: Bool?
    /** List objects to be returned in full (i.e. expanded) - options include: all, stop, route, run, direction, disruption */
    public var expand: [Expand]?

    public init(requests: [V3StopDepartureRequest], dateUtc: Date?, lookBackwards: Bool?, includeCancelled: Bool?, expand: [Expand]?) {
        self.requests = requests
        self.dateUtc = dateUtc
        self.lookBackwards = lookBackwards
        self.includeCancelled = includeCancelled
        self.expand = expand
    }

    public enum CodingKeys: String, CodingKey { 
        case requests
        case dateUtc = "date_utc"
        case lookBackwards = "look_backwards"
        case includeCancelled = "include_cancelled"
        case expand
    }


}

