//
// V3BulkDeparturesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3BulkDeparturesResponse: Codable {

    /** Contains departures for the requested stop and route(s). It includes details as to the route_direction and whether it is still valid. */
    public var responses: [V3BulkDeparturesUpdateResponse]?
    /** A train station, tram stop, bus stop, regional coach stop or Night Bus stop */
    public var stops: [String:V3BulkDeparturesStopResponse]?
    /** Train lines, tram routes, bus routes, regional coach routes, Night Bus routes */
    public var routes: [V3Route]?
    /** Individual trips/services of a route */
    public var runs: [V3Run]?
    /** Directions of travel of route */
    public var directions: [V3Direction]?
    /** Disruption information applicable to relevant routes or stops */
    public var disruptions: [String:V3Disruption]?
    public var status: V3Status?

    public init(responses: [V3BulkDeparturesUpdateResponse]?, stops: [String:V3BulkDeparturesStopResponse]?, routes: [V3Route]?, runs: [V3Run]?, directions: [V3Direction]?, disruptions: [String:V3Disruption]?, status: V3Status?) {
        self.responses = responses
        self.stops = stops
        self.routes = routes
        self.runs = runs
        self.directions = directions
        self.disruptions = disruptions
        self.status = status
    }


}

