//
// V3DeparturesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DeparturesResponse: Codable {

    /** Timetabled and real-time service departures */
    public var departures: [V3Departure]?
    /** A train station, tram stop, bus stop, regional coach stop or Night Bus stop */
    public var stops: [String:V3ResultStop]?
    /** Train lines, tram routes, bus routes, regional coach routes, Night Bus routes */
    public var routes: [String:V3Route]?
    /** Individual trips/services of a route */
    public var runs: [String:V3Run]?
    /** Directions of travel of route */
    public var directions: [String:V3Direction]?
    /** Disruption information applicable to relevant routes or stops */
    public var disruptions: [String:V3Disruption]?
    public var status: V3Status?

    public init(departures: [V3Departure]?, stops: [String:V3ResultStop]?, routes: [String:V3Route]?, runs: [String:V3Run]?, directions: [String:V3Direction]?, disruptions: [String:V3Disruption]?, status: V3Status?) {
        self.departures = departures
        self.stops = stops
        self.routes = routes
        self.runs = runs
        self.directions = directions
        self.disruptions = disruptions
        self.status = status
    }


}

