//
// V3DeparturesSpecificParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DeparturesSpecificParameters: Codable {

    public enum Expand: String, Codable {
        case all = "All"
        case stop = "Stop"
        case route = "Route"
        case run = "Run"
        case direction = "Direction"
        case disruption = "Disruption"
    }
    /** Filter by identifier of direction of travel; values returned by Directions API - /v3/directions/route/{route_id} */
    public var directionId: Int?
    /** Indicates if filtering runs (and their departures) to those that arrive at destination before date_utc (default &#x3D; false). Requires max_results &amp;gt; 0. */
    public var lookBackwards: Bool?
    /** Indicates that stop_id parameter will accept \&quot;GTFS stop_id\&quot; data */
    public var gtfs: Bool?
    /** Filter by the date and time of the request (ISO 8601 UTC format) (default &#x3D; current date and time) */
    public var dateUtc: Date?
    /** Maximum number of results returned */
    public var maxResults: Int?
    /** Indicates if cancelled services (if they exist) are returned (default &#x3D; false) - metropolitan train only */
    public var includeCancelled: Bool?
    /** List objects to be returned in full (i.e. expanded) - options include: all, stop, route, run, direction, disruption */
    public var expand: [Expand]?

    public init(directionId: Int?, lookBackwards: Bool?, gtfs: Bool?, dateUtc: Date?, maxResults: Int?, includeCancelled: Bool?, expand: [Expand]?) {
        self.directionId = directionId
        self.lookBackwards = lookBackwards
        self.gtfs = gtfs
        self.dateUtc = dateUtc
        self.maxResults = maxResults
        self.includeCancelled = includeCancelled
        self.expand = expand
    }

    public enum CodingKeys: String, CodingKey { 
        case directionId = "direction_id"
        case lookBackwards = "look_backwards"
        case gtfs
        case dateUtc = "date_utc"
        case maxResults = "max_results"
        case includeCancelled = "include_cancelled"
        case expand
    }


}

