//
// V3Departure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3Departure: Codable {

    /** Stop identifier */
    public var stopId: Int?
    /** Route identifier */
    public var routeId: Int?
    /** Trip/service run identifier */
    public var runId: Int?
    /** Direction of travel identifier */
    public var directionId: Int?
    /** Disruption information identifier(s) */
    public var disruptionIds: [Int64]?
    /** Scheduled (i.e. timetabled) departure time and date in ISO 8601 UTC format */
    public var scheduledDepartureUtc: Date?
    /** Real-time estimate of departure time and date in ISO 8601 UTC format */
    public var estimatedDepartureUtc: Date?
    /** Indicates if the metropolitan train service is at the platform at the time of query; returns false for other modes */
    public var atPlatform: Bool?
    /** Platform number at stop (metropolitan train only; returns null for other modes) */
    public var platformNumber: String?
    /** Flag indicating special condition for run (e.g. RR Reservations Required, GC Guaranteed Connection, DOO Drop Off Only, PUO Pick Up Only, MO Mondays only, TU Tuesdays only, WE Wednesdays only, TH Thursdays only, FR Fridays only, SS School days only; ignore E flag) */
    public var flags: String?
    /** Chronological sequence of the departure for the run on the route. Order ascendingly by this field to get chronological order (earliest first) of departures with the same route_id and run_id. */
    public var departureSequence: Int?

    public init(stopId: Int?, routeId: Int?, runId: Int?, directionId: Int?, disruptionIds: [Int64]?, scheduledDepartureUtc: Date?, estimatedDepartureUtc: Date?, atPlatform: Bool?, platformNumber: String?, flags: String?, departureSequence: Int?) {
        self.stopId = stopId
        self.routeId = routeId
        self.runId = runId
        self.directionId = directionId
        self.disruptionIds = disruptionIds
        self.scheduledDepartureUtc = scheduledDepartureUtc
        self.estimatedDepartureUtc = estimatedDepartureUtc
        self.atPlatform = atPlatform
        self.platformNumber = platformNumber
        self.flags = flags
        self.departureSequence = departureSequence
    }

    public enum CodingKeys: String, CodingKey { 
        case stopId = "stop_id"
        case routeId = "route_id"
        case runId = "run_id"
        case directionId = "direction_id"
        case disruptionIds = "disruption_ids"
        case scheduledDepartureUtc = "scheduled_departure_utc"
        case estimatedDepartureUtc = "estimated_departure_utc"
        case atPlatform = "at_platform"
        case platformNumber = "platform_number"
        case flags
        case departureSequence = "departure_sequence"
    }


}

