//
// V3DisruptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionResponse: Codable {

    public var disruption: V3Disruption?
    public var status: V3Status?

    public init(disruption: V3Disruption?, status: V3Status?) {
        self.disruption = disruption
        self.status = status
    }


}

