//
// V3DisruptionModesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionModesResponse: Codable {

    /** Transport mode identifiers */
    public var disruptionModes: [V3DisruptionMode]?
    public var status: V3Status?

    public init(disruptionModes: [V3DisruptionMode]?, status: V3Status?) {
        self.disruptionModes = disruptionModes
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case disruptionModes = "disruption_modes"
        case status
    }


}

