//
// V3DirectionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DirectionsResponse: Codable {

    /** Directions of travel of route */
    public var directions: [V3DirectionWithDescription]?
    public var status: V3Status?

    public init(directions: [V3DirectionWithDescription]?, status: V3Status?) {
        self.directions = directions
        self.status = status
    }


}

