//
// V3DisruptionDirection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionDirection: Codable {

    /** Route and direction of travel combination identifier */
    public var routeDirectionId: Int?
    /** Direction of travel identifier */
    public var directionId: Int?
    /** Name of direction of travel */
    public var directionName: String?
    /** Time of service to which disruption applies, in 24 hour clock format (HH:MM:SS) AEDT/AEST; returns null if disruption applies to multiple (or no) services */
    public var serviceTime: String?

    public init(routeDirectionId: Int?, directionId: Int?, directionName: String?, serviceTime: String?) {
        self.routeDirectionId = routeDirectionId
        self.directionId = directionId
        self.directionName = directionName
        self.serviceTime = serviceTime
    }

    public enum CodingKeys: String, CodingKey { 
        case routeDirectionId = "route_direction_id"
        case directionId = "direction_id"
        case directionName = "direction_name"
        case serviceTime = "service_time"
    }


}

