//
// V3DisruptionRoute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionRoute: Codable {

    /** Transport mode identifier */
    public var routeType: Int?
    /** Route identifier */
    public var routeId: Int?
    /** Name of route */
    public var routeName: String?
    /** Route number presented to public (i.e. not route_id) */
    public var routeNumber: String?
    /** GTFS Identifer of the route */
    public var routeGtfsId: String?
    public var direction: V3DisruptionDirection?

    public init(routeType: Int?, routeId: Int?, routeName: String?, routeNumber: String?, routeGtfsId: String?, direction: V3DisruptionDirection?) {
        self.routeType = routeType
        self.routeId = routeId
        self.routeName = routeName
        self.routeNumber = routeNumber
        self.routeGtfsId = routeGtfsId
        self.direction = direction
    }

    public enum CodingKeys: String, CodingKey { 
        case routeType = "route_type"
        case routeId = "route_id"
        case routeName = "route_name"
        case routeNumber = "route_number"
        case routeGtfsId = "route_gtfs_id"
        case direction
    }


}

