//
// V3DisruptionMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionMode: Codable {

    /** Name of disruption mode */
    public var disruptionModeName: String?
    /** Disruption mode identifier */
    public var disruptionMode: Int?

    public init(disruptionModeName: String?, disruptionMode: Int?) {
        self.disruptionModeName = disruptionModeName
        self.disruptionMode = disruptionMode
    }

    public enum CodingKeys: String, CodingKey { 
        case disruptionModeName = "disruption_mode_name"
        case disruptionMode = "disruption_mode"
    }


}

