//
// V3Disruption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3Disruption: Codable {

    /** Disruption information identifier */
    public var disruptionId: Int64?
    /** Headline title summarising disruption information */
    public var title: String?
    /** URL of relevant article on PTV website */
    public var url: String?
    /** Description of the disruption */
    public var description: String?
    /** Status of the disruption (e.g. \&quot;Planned\&quot;, \&quot;Current\&quot;) */
    public var disruptionStatus: String?
    /** Type of disruption */
    public var disruptionType: String?
    /** Date and time disruption information is published on PTV website, in ISO 8601 UTC format */
    public var publishedOn: Date?
    /** Date and time disruption information was last updated by PTV, in ISO 8601 UTC format */
    public var lastUpdated: Date?
    /** Date and time at which disruption begins, in ISO 8601 UTC format */
    public var fromDate: Date?
    /** Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown) */
    public var toDate: Date?
    /** Route relevant to a disruption (if applicable) */
    public var routes: [V3DisruptionRoute]?
    /** Stop relevant to a disruption (if applicable) */
    public var stops: [V3DisruptionStop]?
    public var colour: String?
    public var displayOnBoard: Bool?
    public var displayStatus: Bool?

    public init(disruptionId: Int64?, title: String?, url: String?, description: String?, disruptionStatus: String?, disruptionType: String?, publishedOn: Date?, lastUpdated: Date?, fromDate: Date?, toDate: Date?, routes: [V3DisruptionRoute]?, stops: [V3DisruptionStop]?, colour: String?, displayOnBoard: Bool?, displayStatus: Bool?) {
        self.disruptionId = disruptionId
        self.title = title
        self.url = url
        self.description = description
        self.disruptionStatus = disruptionStatus
        self.disruptionType = disruptionType
        self.publishedOn = publishedOn
        self.lastUpdated = lastUpdated
        self.fromDate = fromDate
        self.toDate = toDate
        self.routes = routes
        self.stops = stops
        self.colour = colour
        self.displayOnBoard = displayOnBoard
        self.displayStatus = displayStatus
    }

    public enum CodingKeys: String, CodingKey { 
        case disruptionId = "disruption_id"
        case title
        case url
        case description
        case disruptionStatus = "disruption_status"
        case disruptionType = "disruption_type"
        case publishedOn = "published_on"
        case lastUpdated = "last_updated"
        case fromDate = "from_date"
        case toDate = "to_date"
        case routes
        case stops
        case colour
        case displayOnBoard = "display_on_board"
        case displayStatus = "display_status"
    }


}

