//
// V3DisruptionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionsResponse: Codable {

    public var disruptions: V3Disruptions?
    public var status: V3Status?

    public init(disruptions: V3Disruptions?, status: V3Status?) {
        self.disruptions = disruptions
        self.status = status
    }


}

