//
// V3DisruptionStop.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3DisruptionStop: Codable {

    /** Stop identifier */
    public var stopId: Int?
    /** Name of stop */
    public var stopName: String?

    public init(stopId: Int?, stopName: String?) {
        self.stopId = stopId
        self.stopName = stopName
    }

    public enum CodingKeys: String, CodingKey { 
        case stopId = "stop_id"
        case stopName = "stop_name"
    }


}

