//
// V3ErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** An error response */

public struct V3ErrorResponse: Codable {

    /** Error message */
    public var message: String?
    public var status: V3Status?

    public init(message: String?, status: V3Status?) {
        self.message = message
        self.status = status
    }


}

