//
// V3OutletResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3OutletResponse: Codable {

    /** myki ticket outlets */
    public var outlets: [V3Outlet]?
    public var status: V3Status?

    public init(outlets: [V3Outlet]?, status: V3Status?) {
        self.outlets = outlets
        self.status = status
    }


}

