//
// V3OutletParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3OutletParameters: Codable {

    /** Maximum number of results returned (default &#x3D; 30) */
    public var maxResults: Int?

    public init(maxResults: Int?) {
        self.maxResults = maxResults
    }

    public enum CodingKeys: String, CodingKey { 
        case maxResults = "max_results"
    }


}

