//
// V3OutletGeolocationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3OutletGeolocationResponse: Codable {

    /** myki ticket outlets */
    public var outlets: [V3OutletGeolocation]?
    public var status: V3Status?

    public init(outlets: [V3OutletGeolocation]?, status: V3Status?) {
        self.outlets = outlets
        self.status = status
    }


}

