//
// V3RouteTypesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3RouteTypesResponse: Codable {

    /** Transport mode identifiers */
    public var routeTypes: [V3RouteType]?
    public var status: V3Status?

    public init(routeTypes: [V3RouteType]?, status: V3Status?) {
        self.routeTypes = routeTypes
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case routeTypes = "route_types"
        case status
    }


}

