//
// V3RouteServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3RouteServiceStatus: Codable {

    public var description: String?
    public var timestamp: Date?

    public init(description: String?, timestamp: Date?) {
        self.description = description
        self.timestamp = timestamp
    }


}

