//
// V3RouteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3RouteResponse: Codable {

    public var route: V3RouteWithStatus?
    public var status: V3Status?

    public init(route: V3RouteWithStatus?, status: V3Status?) {
        self.route = route
        self.status = status
    }


}

