//
// V3RouteWithStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3RouteWithStatus: Codable {

    public var routeServiceStatus: V3RouteServiceStatus?
    /** Transport mode identifier */
    public var routeType: Int?
    /** Route identifier */
    public var routeId: Int?
    /** Name of route */
    public var routeName: String?
    /** Route number presented to public (nb. not route_id) */
    public var routeNumber: String?
    /** GTFS Identifer of the route */
    public var routeGtfsId: String?

    public init(routeServiceStatus: V3RouteServiceStatus?, routeType: Int?, routeId: Int?, routeName: String?, routeNumber: String?, routeGtfsId: String?) {
        self.routeServiceStatus = routeServiceStatus
        self.routeType = routeType
        self.routeId = routeId
        self.routeName = routeName
        self.routeNumber = routeNumber
        self.routeGtfsId = routeGtfsId
    }

    public enum CodingKeys: String, CodingKey { 
        case routeServiceStatus = "route_service_status"
        case routeType = "route_type"
        case routeId = "route_id"
        case routeName = "route_name"
        case routeNumber = "route_number"
        case routeGtfsId = "route_gtfs_id"
    }


}

