//
// V3RunResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3RunResponse: Codable {

    public var run: V3Run?
    public var status: V3Status?

    public init(run: V3Run?, status: V3Status?) {
        self.run = run
        self.status = status
    }


}

