//
// V3StopDepartureRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopDepartureRequest: Codable {

    public enum RouteType: Int, Codable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
    }
    /** Number identifying transport mode; values returned via RouteTypes API */
    public var routeType: RouteType?
    /** Identifier of stop; values returned by Stops API */
    public var stopId: Int?
    /** Maximum number of results returned */
    public var maxResults: Int?
    /** Indicates that stop_id parameter will accept \&quot;GTFS stop_id\&quot; data and route_directions[x].route_id parameters will accept route_gtfs_id data */
    public var gtfs: Bool?
    /** The route directions to find departures for at this stop. */
    public var routeDirections: [V3StopDepartureRequestRouteDirection]

    public init(routeType: RouteType?, stopId: Int?, maxResults: Int?, gtfs: Bool?, routeDirections: [V3StopDepartureRequestRouteDirection]) {
        self.routeType = routeType
        self.stopId = stopId
        self.maxResults = maxResults
        self.gtfs = gtfs
        self.routeDirections = routeDirections
    }

    public enum CodingKeys: String, CodingKey { 
        case routeType = "route_type"
        case stopId = "stop_id"
        case maxResults = "max_results"
        case gtfs
        case routeDirections = "route_directions"
    }


}

