//
// V3StopAmenityDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopAmenityDetails: Codable {

    /** Indicates if there is a public toilet at or near the stop */
    public var toilet: Bool?
    /** Indicates if there is a taxi rank at or near the stop */
    public var taxiRank: Bool?
    /** The number of free car parking spots at the stop */
    public var carParking: String?
    /** Indicates if there are CCTV (i.e. closed circuit television) cameras at the stop */
    public var cctv: Bool?

    public init(toilet: Bool?, taxiRank: Bool?, carParking: String?, cctv: Bool?) {
        self.toilet = toilet
        self.taxiRank = taxiRank
        self.carParking = carParking
        self.cctv = cctv
    }

    public enum CodingKeys: String, CodingKey { 
        case toilet
        case taxiRank = "taxi_rank"
        case carParking = "car_parking"
        case cctv
    }


}

