//
// V3StopGps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopGps: Codable {

    /** Geographic coordinate of latitude at stop */
    public var latitude: Float?
    /** Geographic coordinate of longitude at stop */
    public var longitude: Float?

    public init(latitude: Float?, longitude: Float?) {
        self.latitude = latitude
        self.longitude = longitude
    }


}

