//
// V3StopResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopResponse: Codable {

    public var stop: V3StopDetails?
    /** Disruption information applicable to relevant routes or stops */
    public var disruptions: [String:V3Disruption]?
    public var status: V3Status?

    public init(stop: V3StopDetails?, disruptions: [String:V3Disruption]?, status: V3Status?) {
        self.stop = stop
        self.disruptions = disruptions
        self.status = status
    }


}

