//
// V3StopOnRoute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopOnRoute: Codable {

    /** Disruption information identifier(s) */
    public var disruptionIds: [Int64]?
    /** suburb of stop */
    public var stopSuburb: String?
    /** Name of stop */
    public var stopName: String?
    /** Stop identifier */
    public var stopId: Int?
    /** Transport mode identifier */
    public var routeType: Int?
    /** Geographic coordinate of latitude at stop */
    public var stopLatitude: Float?
    /** Geographic coordinate of longitude at stop */
    public var stopLongitude: Float?
    /** Sequence of the stop on the route/run; return 0 when route_id or run_id not specified. Order ascendingly by this field (when non zero) to get physical order (earliest first) of stops on the route_id/run_id. */
    public var stopSequence: Int?

    public init(disruptionIds: [Int64]?, stopSuburb: String?, stopName: String?, stopId: Int?, routeType: Int?, stopLatitude: Float?, stopLongitude: Float?, stopSequence: Int?) {
        self.disruptionIds = disruptionIds
        self.stopSuburb = stopSuburb
        self.stopName = stopName
        self.stopId = stopId
        self.routeType = routeType
        self.stopLatitude = stopLatitude
        self.stopLongitude = stopLongitude
        self.stopSequence = stopSequence
    }

    public enum CodingKeys: String, CodingKey { 
        case disruptionIds = "disruption_ids"
        case stopSuburb = "stop_suburb"
        case stopName = "stop_name"
        case stopId = "stop_id"
        case routeType = "route_type"
        case stopLatitude = "stop_latitude"
        case stopLongitude = "stop_longitude"
        case stopSequence = "stop_sequence"
    }


}

