//
// V3StopLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopLocation: Codable {

    public var gps: V3StopGps?

    public init(gps: V3StopGps?) {
        self.gps = gps
    }


}

