//
// V3StopDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopDetails: Codable {

    /** Disruption information identifier(s) */
    public var disruptionIds: [Int64]?
    /** Type of metropolitan train station (i.e. \&quot;Premium\&quot;, \&quot;Host\&quot; or \&quot;Unstaffed\&quot; station); returns null for V/Line train */
    public var stationType: String?
    /** The definition applicable to the station_type; returns null for V/Line train */
    public var stationDescription: String?
    /** Transport mode identifier */
    public var routeType: Int?
    public var stopLocation: V3StopLocation?
    public var stopAmenities: V3StopAmenityDetails?
    public var stopAccessibility: V3StopAccessibility?
    public var stopStaffing: V3StopStaffing?
    /** Stop identifier */
    public var stopId: Int?
    /** Name of stop */
    public var stopName: String?

    public init(disruptionIds: [Int64]?, stationType: String?, stationDescription: String?, routeType: Int?, stopLocation: V3StopLocation?, stopAmenities: V3StopAmenityDetails?, stopAccessibility: V3StopAccessibility?, stopStaffing: V3StopStaffing?, stopId: Int?, stopName: String?) {
        self.disruptionIds = disruptionIds
        self.stationType = stationType
        self.stationDescription = stationDescription
        self.routeType = routeType
        self.stopLocation = stopLocation
        self.stopAmenities = stopAmenities
        self.stopAccessibility = stopAccessibility
        self.stopStaffing = stopStaffing
        self.stopId = stopId
        self.stopName = stopName
    }

    public enum CodingKeys: String, CodingKey { 
        case disruptionIds = "disruption_ids"
        case stationType = "station_type"
        case stationDescription = "station_description"
        case routeType = "route_type"
        case stopLocation = "stop_location"
        case stopAmenities = "stop_amenities"
        case stopAccessibility = "stop_accessibility"
        case stopStaffing = "stop_staffing"
        case stopId = "stop_id"
        case stopName = "stop_name"
    }


}

