//
// V3StopAccessibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopAccessibility: Codable {

    /** Indicates if there is lighting at the stop */
    public var lighting: Bool?
    /** Indicates the platform number for xivic information (Platform 0 indicates general stop facilities) */
    public var platformNumber: Int?
    /** Indicates if there is at least one audio customer information at the stop/platform */
    public var audioCustomerInformation: Bool?
    /** Indicates if there is at least one accessible escalator at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992) */
    public var escalator: Bool?
    /** Indicates if there is a hearing loop facility at the stop/platform */
    public var hearingLoop: Bool?
    /** Indicates if there is an elevator at the stop/platform */
    public var lift: Bool?
    /** Indicates if there are stairs available in the stop */
    public var stairs: Bool?
    /** Indicates if the stop is accessible */
    public var stopAccessible: Bool?
    /** Indicates if there are tactile tiles (also known as tactile ground surface indicators, or TGSIs) at the stop */
    public var tactileGroundSurfaceIndicator: Bool?
    /** Indicates if there is a general waiting area at the stop */
    public var waitingRoom: Bool?
    public var wheelchair: V3StopAccessibilityWheelchair?

    public init(lighting: Bool?, platformNumber: Int?, audioCustomerInformation: Bool?, escalator: Bool?, hearingLoop: Bool?, lift: Bool?, stairs: Bool?, stopAccessible: Bool?, tactileGroundSurfaceIndicator: Bool?, waitingRoom: Bool?, wheelchair: V3StopAccessibilityWheelchair?) {
        self.lighting = lighting
        self.platformNumber = platformNumber
        self.audioCustomerInformation = audioCustomerInformation
        self.escalator = escalator
        self.hearingLoop = hearingLoop
        self.lift = lift
        self.stairs = stairs
        self.stopAccessible = stopAccessible
        self.tactileGroundSurfaceIndicator = tactileGroundSurfaceIndicator
        self.waitingRoom = waitingRoom
        self.wheelchair = wheelchair
    }

    public enum CodingKeys: String, CodingKey { 
        case lighting
        case platformNumber = "platform_number"
        case audioCustomerInformation = "audio_customer_information"
        case escalator
        case hearingLoop = "hearing_loop"
        case lift
        case stairs
        case stopAccessible = "stop_accessible"
        case tactileGroundSurfaceIndicator = "tactile_ground_surface_indicator"
        case waitingRoom = "waiting_room"
        case wheelchair
    }


}

