//
// V3Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3Status: Codable {

    public enum Health: Int, Codable {
        case _0 = 0
        case _1 = 1
    }
    /** API Version number */
    public var version: String?
    /** API system health status (0&#x3D;offline, 1&#x3D;online) */
    public var health: Health?

    public init(version: String?, health: Health?) {
        self.version = version
        self.health = health
    }


}

