//
// V3StopsOnRouteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3StopsOnRouteResponse: Codable {

    /** Train stations, tram stops, bus stops, regional coach stops or Night Bus stops */
    public var stops: [V3StopOnRoute]?
    /** Disruption information applicable to relevant routes or stops */
    public var disruptions: [String:V3Disruption]?
    public var status: V3Status?

    public init(stops: [V3StopOnRoute]?, disruptions: [String:V3Disruption]?, status: V3Status?) {
        self.stops = stops
        self.disruptions = disruptions
        self.status = status
    }


}

