//
// V3VehiclePosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3VehiclePosition: Codable {

    /** Geographic coordinate of latitude of the vehicle when known. May be null.              Only available for some bus runs. */
    public var latitude: Float?
    /** Geographic coordinate of longitude of the vehicle when known.               Only available for some bus runs. */
    public var longitude: Float?
    /** Compass bearing of the vehicle when known, clockwise from True North, i.e., 0 is North and 90 is East. May be null.              Only available for some bus runs. */
    public var bearing: Float?
    /** Supplier of vehicle position data. */
    public var supplier: String?

    public init(latitude: Float?, longitude: Float?, bearing: Float?, supplier: String?) {
        self.latitude = latitude
        self.longitude = longitude
        self.bearing = bearing
        self.supplier = supplier
    }


}

