//
// V3VehicleDescriptor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V3VehicleDescriptor: Codable {

    /** Operator name of the vehicle such as \&quot;Metro Trains Melbourne\&quot;, \&quot;Yarra Trams\&quot;, \&quot;Ventura Bus Line\&quot;, \&quot;CDC\&quot; or \&quot;Sita Bus Lines\&quot; . May be null/empty.              Only available for train, tram, v/line and some bus runs. */
    public var _operator: String?
    /** Operator identifier of the vehicle such as \&quot;26094\&quot;. May be null/empty. Only available for some tram and bus runs. */
    public var id: String?
    /** Indicator if vehicle has a low floor. May be null. Only available for some tram runs. */
    public var lowFloor: Bool?
    /** Indicator if vehicle is air conditioned. May be null. Only available for some tram runs. */
    public var airConditioned: Bool?
    /** Vehicle description such as \&quot;6 Car Comeng\&quot;, \&quot;6 Car Xtrapolis\&quot;, \&quot;3 Car Comeng\&quot;, \&quot;6 Car Siemens\&quot;, \&quot;3 Car Siemens\&quot;. May be null/empty.              Only available for some metropolitan train runs. */
    public var description: String?
    /** Supplier of vehicle descriptor data. */
    public var supplier: String?

    public init(_operator: String?, id: String?, lowFloor: Bool?, airConditioned: Bool?, description: String?, supplier: String?) {
        self._operator = _operator
        self.id = id
        self.lowFloor = lowFloor
        self.airConditioned = airConditioned
        self.description = description
        self.supplier = supplier
    }

    public enum CodingKeys: String, CodingKey { 
        case _operator = "operator"
        case id
        case lowFloor = "low_floor"
        case airConditioned = "air_conditioned"
        case description
        case supplier
    }


}

